# Generated by Django 4.2.30 on 2026-08-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_title_fk'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='squad_required_unless_scrum_master',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['scrum_master', 'chapter_lead']), ('squad__isnull', False), _connector='OR'), name='squad_required_unless_scrum_master_or_chapter_lead'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'chapter_lead')), fields=('title',), name='one_chapter_lead_per_title'),
        ),
    ]
