# Generated by Django 4.2.30 on 2026-08-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_squad_required_unless_scrum_master_and_more'),
        ('org', '0007_seed_scrum_master_admin_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='squad_required_unless_scrum_master_or_chapter_lead',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('chapter_lead', 'Chapter Lead'), ('end_user', 'End User')], default='end_user', max_length=20),
        ),
    ]
