# Generated by Django 4.2.30 on 2026-08-20 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('refused', 'Refused'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holiday_decisions', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holiday_requests', to=settings.AUTH_USER_MODEL)),
                ('routed_chapter_lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='HolidayRequestDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_part', models.CharField(choices=[('full', 'Full day'), ('half', 'Half day')], default='full', max_length=4)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='holidays.holidayrequest')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('request', 'date')},
            },
        ),
    ]
