# Generated by Django 4.2.30 on 2026-08-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holidayrequest',
            options={'ordering': ['-submitted_at'], 'permissions': [('edit_any_holiday_silently', "Can directly edit any user's holiday requests without notifying the chapter lead")]},
        ),
    ]
