# Generated by Django 4.2.30 on 2026-08-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0003_per_day_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayrequestday',
            name='decision_reason',
            field=models.TextField(blank=True),
        ),
    ]
