# Generated by Django 4.2.30 on 2026-08-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0004_alter_holidayrequestday_decision_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayrequestday',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('refused', 'Refused'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
