# Generated by Django 4.2.30 on 2026-08-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0005_alter_holidayrequestday_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayrequestday',
            name='day_part',
            field=models.CharField(choices=[('full', 'Full day'), ('half', '1/2 day')], default='full', max_length=4),
        ),
    ]
