# Generated by Django 4.2.30 on 2026-08-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('quarter', models.PositiveSmallIntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('name', models.CharField(help_text='e.g. SP1, SP2, SP3', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='org.tribe')),
            ],
            options={
                'ordering': ['tribe__name', 'year', 'quarter', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('tribe', 'Tribe'), ('cluster', 'Cluster'), ('squad', 'Squad')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='org.cluster')),
                ('squad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='org.squad')),
                ('tribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='org.tribe')),
            ],
            options={
                'ordering': ['tribe__name', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='BankHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('tribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_holidays', to='org.tribe')),
            ],
            options={
                'ordering': ['tribe__name', 'date'],
            },
        ),
        migrations.AddConstraint(
            model_name='sprint',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='sprint_end_after_start'),
        ),
        migrations.AlterUniqueTogether(
            name='sprint',
            unique_together={('tribe', 'year', 'quarter', 'name')},
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('cluster__isnull', True), ('scope', 'tribe'), ('squad__isnull', True)), models.Q(('cluster__isnull', False), ('scope', 'cluster'), ('squad__isnull', True)), models.Q(('scope', 'squad'), ('squad__isnull', False)), _connector='OR'), name='event_scope_matches_fk'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='event_end_after_start'),
        ),
        migrations.AlterUniqueTogether(
            name='bankholiday',
            unique_together={('tribe', 'date')},
        ),
    ]
