# Generated by Django 4.2.30 on 2026-08-20 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['tribe__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='org.cluster')),
            ],
            options={
                'ordering': ['cluster__tribe__name', 'cluster__name', 'name'],
                'unique_together': {('cluster', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cluster',
            name='tribe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='org.tribe'),
        ),
        migrations.CreateModel(
            name='SquadWatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='org.squad')),
            ],
            options={
                'ordering': ['squad', 'email'],
                'unique_together': {('squad', 'email')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cluster',
            unique_together={('tribe', 'name')},
        ),
        migrations.CreateModel(
            name='ChapterLeadAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('scrum_master', 'Scrum Master'), ('product_owner', 'Product Owner'), ('data_scientist', 'Data Scientist'), ('ai_engineer', 'AI Engineer'), ('business_analyst', 'Business Analyst')], max_length=30)),
                ('chapter_lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapter_lead_for', to=settings.AUTH_USER_MODEL)),
                ('tribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_lead_assignments', to='org.tribe')),
            ],
            options={
                'ordering': ['tribe__name', 'title'],
                'unique_together': {('tribe', 'title')},
            },
        ),
    ]
