# Generated by Django 4.2.30 on 2026-08-20 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('org', '0003_chapterleadassignment_title_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapterleadassignment',
            options={'ordering': ['tribe__name', 'title__name'], 'verbose_name': 'backup chapter lead assignment', 'verbose_name_plural': 'backup chapter lead assignments'},
        ),
        migrations.AlterUniqueTogether(
            name='chapterleadassignment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='chapterleadassignment',
            name='chapter_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapter_lead_for', to=settings.AUTH_USER_MODEL, verbose_name='backup approver'),
        ),
        migrations.AlterUniqueTogether(
            name='chapterleadassignment',
            unique_together={('tribe', 'title', 'chapter_lead')},
        ),
    ]
