# Generated by Django 4.2.30 on 2026-08-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_cleanup_redundant_backup_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='grants_admin_access',
            field=models.BooleanField(default=False, help_text='Anyone holding this title becomes an admin of the app (can reach /admin/ and manage the tribe).'),
        ),
    ]
